### ISSUE TITLE
Offset of internal reference targets

### ISSUE THREAD

**Issue by crayxt** [howistart/howistart.org#3]
When you click on internal link, the target is positioned behind the top header, so you have to scroll up a little to actually see it. Check this http://howistart.org/posts/go/1#setting-up-your-environment

**Comment by tsloughter** [comment]
Ah yea, forgot to figure out a fix for that. I guess I could just make the navbar not sticky.

**Comment by crayxt** [comment]
Ping

**Comment by tsloughter** [comment]
Thanks for the ping! I've deployed the change.
